### PR TITLE
Fix Remote headless

### PR DESCRIPTION
**Pull request by h98aaron**
* Forward Options to driver.Remote(...)

### CODE REVIEW

**Comment by roigreenberg** [comment]
Hi.
Can you please explain what is this "headless" state?
will it reduce the selenium CPU usage?

**Comment by h98aaron** [comment]
@roigreenberg 

> will it reduce the selenium CPU usage?

Yes, because it's not started the [XVFB](https://en.wikipedia.org/wiki/Xvfb) - X virtual sever

PR is relevant for remote, when you run selenium in a separate container,
just start selenium container with `-e START_XCFB=false` and `WhatsAPIDriver(headless=True)` and you ready.

**Comment by roigreenberg** [comment]
I'm using containers, so it sounds great, but how do I get the QR?

**Comment by h98aaron** [comment]
https://github.com/open-wa/wa-automate-python#4-get-the-qr-in-one-of-these-ways

**Pull request merged**
